// The currency table and flag derivation
// Extracted from App.jsx — pure logic, no React, so it can be unit tested.

// ─── CURRENCIES ───────────────────────────────────────────────────────────────
const CURRENCIES = [
  {code:"GBP",name:"British Pound",symbol:"£",locale:"en-GB"},
  {code:"USD",name:"US Dollar",symbol:"$",locale:"en-US"},
  {code:"EUR",name:"Euro",symbol:"€",locale:"de-DE"},
  {code:"JPY",name:"Japanese Yen",symbol:"¥",locale:"ja-JP"},
  {code:"CAD",name:"Canadian Dollar",symbol:"CA$",locale:"en-CA"},
  {code:"AUD",name:"Australian Dollar",symbol:"A$",locale:"en-AU"},
  {code:"CHF",name:"Swiss Franc",symbol:"Fr",locale:"de-CH"},
  {code:"CNY",name:"Chinese Yuan",symbol:"¥",locale:"zh-CN"},
  {code:"HKD",name:"Hong Kong Dollar",symbol:"HK$",locale:"en-HK"},
  {code:"NZD",name:"New Zealand Dollar",symbol:"NZ$",locale:"en-NZ"},
  {code:"SEK",name:"Swedish Krona",symbol:"kr",locale:"sv-SE"},
  {code:"NOK",name:"Norwegian Krone",symbol:"kr",locale:"nb-NO"},
  {code:"DKK",name:"Danish Krone",symbol:"kr",locale:"da-DK"},
  {code:"SGD",name:"Singapore Dollar",symbol:"S$",locale:"en-SG"},
  {code:"KRW",name:"South Korean Won",symbol:"₩",locale:"ko-KR"},
  {code:"INR",name:"Indian Rupee",symbol:"₹",locale:"en-IN"},
  {code:"MXN",name:"Mexican Peso",symbol:"$",locale:"es-MX"},
  {code:"BRL",name:"Brazilian Real",symbol:"R$",locale:"pt-BR"},
  {code:"ZAR",name:"South African Rand",symbol:"R",locale:"en-ZA"},
  {code:"TRY",name:"Turkish Lira",symbol:"₺",locale:"tr-TR"},
  {code:"PLN",name:"Polish Złoty",symbol:"zł",locale:"pl-PL"},
  {code:"THB",name:"Thai Baht",symbol:"฿",locale:"th-TH"},
  {code:"MYR",name:"Malaysian Ringgit",symbol:"RM",locale:"ms-MY"},
  {code:"IDR",name:"Indonesian Rupiah",symbol:"Rp",locale:"id-ID"},
  {code:"PHP",name:"Philippine Peso",symbol:"₱",locale:"en-PH"},
  {code:"HUF",name:"Hungarian Forint",symbol:"Ft",locale:"hu-HU"},
  {code:"CZK",name:"Czech Koruna",symbol:"Kč",locale:"cs-CZ"},
  {code:"ILS",name:"Israeli Shekel",symbol:"₪",locale:"he-IL"},
  {code:"AED",name:"UAE Dirham",symbol:"د.إ",locale:"ar-AE"},
  {code:"SAR",name:"Saudi Riyal",symbol:"﷼",locale:"ar-SA"},
  {code:"KWD",name:"Kuwaiti Dinar",symbol:"KD",locale:"ar-KW"},
  {code:"QAR",name:"Qatari Riyal",symbol:"QR",locale:"ar-QA"},
  {code:"BHD",name:"Bahraini Dinar",symbol:"BD",locale:"ar-BH"},
  {code:"OMR",name:"Omani Rial",symbol:"OMR",locale:"ar-OM"},
  {code:"JOD",name:"Jordanian Dinar",symbol:"JD",locale:"ar-JO"},
  {code:"EGP",name:"Egyptian Pound",symbol:"E£",locale:"ar-EG"},
  {code:"MAD",name:"Moroccan Dirham",symbol:"MAD",locale:"ar-MA"},
  {code:"NGN",name:"Nigerian Naira",symbol:"₦",locale:"en-NG"},
  {code:"GHS",name:"Ghanaian Cedi",symbol:"₵",locale:"en-GH"},
  {code:"KES",name:"Kenyan Shilling",symbol:"Ksh",locale:"sw-KE"},
  {code:"UGX",name:"Ugandan Shilling",symbol:"USh",locale:"en-UG"},
  {code:"TZS",name:"Tanzanian Shilling",symbol:"TSh",locale:"sw-TZ"},
  {code:"ETB",name:"Ethiopian Birr",symbol:"Br",locale:"am-ET"},
  {code:"XOF",name:"W. African CFA Franc",symbol:"CFA",locale:"fr-SN"},
  {code:"XAF",name:"C. African CFA Franc",symbol:"FCFA",locale:"fr-CM"},
  {code:"PKR",name:"Pakistani Rupee",symbol:"₨",locale:"ur-PK"},
  {code:"BDT",name:"Bangladeshi Taka",symbol:"৳",locale:"bn-BD"},
  {code:"LKR",name:"Sri Lankan Rupee",symbol:"Rs",locale:"si-LK"},
  {code:"NPR",name:"Nepalese Rupee",symbol:"Rs",locale:"ne-NP"},
  {code:"VND",name:"Vietnamese Dong",symbol:"₫",locale:"vi-VN"},
  {code:"TWD",name:"New Taiwan Dollar",symbol:"NT$",locale:"zh-TW"},
  {code:"KHR",name:"Cambodian Riel",symbol:"៛",locale:"km-KH"},
  {code:"MMK",name:"Myanmar Kyat",symbol:"K",locale:"my-MM"},
  {code:"RUB",name:"Russian Ruble",symbol:"₽",locale:"ru-RU"},
  {code:"UAH",name:"Ukrainian Hryvnia",symbol:"₴",locale:"uk-UA"},
  {code:"KZT",name:"Kazakhstani Tenge",symbol:"₸",locale:"kk-KZ"},
  {code:"GEL",name:"Georgian Lari",symbol:"₾",locale:"ka-GE"},
  {code:"AMD",name:"Armenian Dram",symbol:"֏",locale:"hy-AM"},
  {code:"AZN",name:"Azerbaijani Manat",symbol:"₼",locale:"az-AZ"},
  {code:"UZS",name:"Uzbekistani Som",symbol:"soʻm",locale:"uz-UZ"},
  {code:"RON",name:"Romanian Leu",symbol:"lei",locale:"ro-RO"},
  {code:"BGN",name:"Bulgarian Lev",symbol:"лв",locale:"bg-BG"},
  {code:"RSD",name:"Serbian Dinar",symbol:"din",locale:"sr-RS"},
  {code:"HRK",name:"Croatian Kuna",symbol:"kn",locale:"hr-HR"},
  {code:"ISK",name:"Icelandic Krona",symbol:"kr",locale:"is-IS"},
  {code:"CLP",name:"Chilean Peso",symbol:"$",locale:"es-CL"},
  {code:"ARS",name:"Argentine Peso",symbol:"$",locale:"es-AR"},
  {code:"COP",name:"Colombian Peso",symbol:"$",locale:"es-CO"},
  {code:"PEN",name:"Peruvian Sol",symbol:"S/",locale:"es-PE"},
  {code:"BOB",name:"Bolivian Boliviano",symbol:"Bs",locale:"es-BO"},
  {code:"PYG",name:"Paraguayan Guaraní",symbol:"₲",locale:"es-PY"},
  {code:"UYU",name:"Uruguayan Peso",symbol:"$U",locale:"es-UY"},
  {code:"DZD",name:"Algerian Dinar",symbol:"DA",locale:"ar-DZ"},
  {code:"TND",name:"Tunisian Dinar",symbol:"DT",locale:"ar-TN"},
  {code:"LYD",name:"Libyan Dinar",symbol:"LD",locale:"ar-LY"},
  // ── Remaining ISO 4217 currencies, alphabetical by name ──────────────────
  {code:"AFN",name:"Afghan Afghani",symbol:"؋",locale:"fa-AF"},
  {code:"ALL",name:"Albanian Lek",symbol:"ALL",locale:"sq-AL"},
  {code:"AOA",name:"Angolan Kwanza",symbol:"Kz",locale:"pt-AO"},
  {code:"AWG",name:"Aruban Florin",symbol:"AWG",locale:"nl-AW"},
  {code:"BSD",name:"Bahamian Dollar",symbol:"$",locale:"en-BS"},
  {code:"BBD",name:"Barbadian Dollar",symbol:"$",locale:"en-BB"},
  {code:"BYN",name:"Belarusian Ruble",symbol:"BYN",locale:"ru-BY"},
  {code:"BZD",name:"Belize Dollar",symbol:"$",locale:"en-BZ"},
  {code:"BMD",name:"Bermudan Dollar",symbol:"$",locale:"en-BM"},
  {code:"BTN",name:"Bhutanese Ngultrum",symbol:"BTN",locale:"dz-BT"},
  {code:"BAM",name:"Bosnia-Herzegovina Convertible Mark",symbol:"KM",locale:"bs-BA"},
  {code:"BWP",name:"Botswanan Pula",symbol:"P",locale:"en-BW"},
  {code:"BND",name:"Brunei Dollar",symbol:"$",locale:"ms-BN"},
  {code:"BIF",name:"Burundian Franc",symbol:"BIF",locale:"rn-BI"},
  {code:"CVE",name:"Cape Verdean Escudo",symbol:"CVE",locale:"pt-CV"},
  {code:"KYD",name:"Cayman Islands Dollar",symbol:"$",locale:"en-KY"},
  {code:"XPF",name:"CFP Franc",symbol:"CFPF",locale:"fr-PF"},
  {code:"KMF",name:"Comorian Franc",symbol:"CF",locale:"ar-KM"},
  {code:"CDF",name:"Congolese Franc",symbol:"CDF",locale:"fr-CD"},
  {code:"CRC",name:"Costa Rican Colón",symbol:"₡",locale:"es-CR"},
  {code:"CUP",name:"Cuban Peso",symbol:"$",locale:"es-CU"},
  {code:"DJF",name:"Djiboutian Franc",symbol:"DJF",locale:"fr-DJ"},
  {code:"DOP",name:"Dominican Peso",symbol:"$",locale:"es-DO"},
  {code:"XCD",name:"East Caribbean Dollar",symbol:"$",locale:"en-AG"},
  {code:"ERN",name:"Eritrean Nakfa",symbol:"ERN",locale:"ti-ER"},
  {code:"FKP",name:"Falkland Islands Pound",symbol:"£",locale:"en-FK"},
  {code:"FJD",name:"Fijian Dollar",symbol:"$",locale:"en-FJ"},
  {code:"GMD",name:"Gambian Dalasi",symbol:"GMD",locale:"en-GM"},
  {code:"GIP",name:"Gibraltar Pound",symbol:"£",locale:"en-GI"},
  {code:"GTQ",name:"Guatemalan Quetzal",symbol:"Q",locale:"es-GT"},
  {code:"GNF",name:"Guinean Franc",symbol:"FG",locale:"fr-GN"},
  {code:"GYD",name:"Guyanaese Dollar",symbol:"$",locale:"en-GY"},
  {code:"HTG",name:"Haitian Gourde",symbol:"HTG",locale:"ht-HT"},
  {code:"HNL",name:"Honduran Lempira",symbol:"L",locale:"es-HN"},
  {code:"IRR",name:"Iranian Rial",symbol:"IRR",locale:"fa-IR"},
  {code:"IQD",name:"Iraqi Dinar",symbol:"IQD",locale:"ar-IQ"},
  {code:"JMD",name:"Jamaican Dollar",symbol:"$",locale:"en-JM"},
  {code:"KGS",name:"Kyrgyz Som",symbol:"⃀",locale:"ky-KG"},
  {code:"LAK",name:"Laotian Kip",symbol:"₭",locale:"lo-LA"},
  {code:"LBP",name:"Lebanese Pound",symbol:"L£",locale:"ar-LB"},
  {code:"LSL",name:"Lesotho Loti",symbol:"LSL",locale:"st-LS"},
  {code:"LRD",name:"Liberian Dollar",symbol:"$",locale:"en-LR"},
  {code:"MOP",name:"Macanese Pataca",symbol:"MOP",locale:"zh-MO"},
  {code:"MKD",name:"Macedonian Denar",symbol:"MKD",locale:"mk-MK"},
  {code:"MGA",name:"Malagasy Ariary",symbol:"Ar",locale:"mg-MG"},
  {code:"MWK",name:"Malawian Kwacha",symbol:"MWK",locale:"en-MW"},
  {code:"MVR",name:"Maldivian Rufiyaa",symbol:"MVR",locale:"dv-MV"},
  {code:"MRU",name:"Mauritanian Ouguiya",symbol:"MRU",locale:"ar-MR"},
  {code:"MUR",name:"Mauritian Rupee",symbol:"Rs",locale:"fr-MU"},
  {code:"MDL",name:"Moldovan Leu",symbol:"MDL",locale:"ro-MD"},
  {code:"MNT",name:"Mongolian Tugrik",symbol:"₮",locale:"mn-MN"},
  {code:"MZN",name:"Mozambican Metical",symbol:"MZN",locale:"pt-MZ"},
  {code:"NAD",name:"Namibian Dollar",symbol:"$",locale:"af-NA"},
  {code:"ANG",name:"Netherlands Antillean Guilder",symbol:"ANG",locale:"nl-CW"},
  {code:"NIO",name:"Nicaraguan Córdoba",symbol:"C$",locale:"es-NI"},
  {code:"KPW",name:"North Korean Won",symbol:"₩",locale:"ko-KP"},
  {code:"PAB",name:"Panamanian Balboa",symbol:"PAB",locale:"es-PA"},
  {code:"PGK",name:"Papua New Guinean Kina",symbol:"PGK",locale:"tpi-PG"},
  {code:"RWF",name:"Rwandan Franc",symbol:"RF",locale:"rw-RW"},
  {code:"WST",name:"Samoan Tala",symbol:"WST",locale:"sm-WS"},
  {code:"STN",name:"São Tomé & Príncipe Dobra",symbol:"Db",locale:"pt-ST"},
  {code:"SCR",name:"Seychellois Rupee",symbol:"SCR",locale:"fr-SC"},
  {code:"SLE",name:"Sierra Leonean Leone",symbol:"Le",locale:"en-SL"},
  {code:"SBD",name:"Solomon Islands Dollar",symbol:"$",locale:"en-SB"},
  {code:"SOS",name:"Somali Shilling",symbol:"SOS",locale:"so-SO"},
  {code:"SSP",name:"South Sudanese Pound",symbol:"£",locale:"en-SS"},
  {code:"SHP",name:"St. Helena Pound",symbol:"£",locale:"en-SH"},
  {code:"SDG",name:"Sudanese Pound",symbol:"SDG",locale:"ar-SD"},
  {code:"SRD",name:"Surinamese Dollar",symbol:"$",locale:"nl-SR"},
  {code:"SZL",name:"Swazi Lilangeni",symbol:"SZL",locale:"en-SZ"},
  {code:"SYP",name:"Syrian Pound",symbol:"£",locale:"ar-SY"},
  {code:"TJS",name:"Tajikistani Somoni",symbol:"TJS",locale:"tg-TJ"},
  {code:"TOP",name:"Tongan Paʻanga",symbol:"T$",locale:"to-TO"},
  {code:"TTD",name:"Trinidad & Tobago Dollar",symbol:"$",locale:"en-TT"},
  {code:"TMT",name:"Turkmenistani Manat",symbol:"TMT",locale:"tk-TM"},
  {code:"VUV",name:"Vanuatu Vatu",symbol:"VUV",locale:"bi-VU"},
  {code:"VES",name:"Venezuelan Bolívar",symbol:"VES",locale:"es-VE"},
  {code:"YER",name:"Yemeni Rial",symbol:"YER",locale:"ar-YE"},
  {code:"ZMW",name:"Zambian Kwacha",symbol:"ZK",locale:"en-ZM"},
  {code:"ZWG",name:"Zimbabwean Gold",symbol:"ZiG",locale:"en-ZW"},
];
// Derive flag emoji from locale country code (e.g. "en-GB" → 🇬🇧)
const flagEmoji = locale => {
  const cc = (locale.split("-")[1] || "").toUpperCase();
  if (cc.length !== 2) return "🌐";
  return String.fromCodePoint(...cc.split("").map(c => 0x1F1E6 + c.charCodeAt(0) - 65));
};

export { CURRENCIES, flagEmoji };
